gateway-solution/my-gateway-api.xml:
  url: "/example"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
gateway-solution/my-gateway-apis.xml:
  url: "/example"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
